export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export JAVA_HOME=$(/usr/libexec/java_home -v 11)
export PATH=$PATH:$JAVA_HOME/bin

alias "tml"="$HOME/scripts/mac/show_log_tm.sh"
alias "tmp"="$HOME/scripts/mac/show_tm_lsof.sh"
alias "dreamx"="$HOME/scripts/mac/dreamx.sh"

